### ISSUE TITLE
Add CI Integration

### ISSUE THREAD

**Issue by arschles** [kubernetes-client/typescript#11]
A hosted CI system (I'm partial to CircleCI) should automatically run tests on pull requests (every push to a branch for which a pull request is open) and on master. The `README` should ideally also contain a "build badge" image to indicate whether the build on master is passing or failing.

The CI system should run `npm test` to run the tests.

**Comment by mbohlool** [comment]
We have Travis CI enabled for the org. I am not against CircleCI or any other CIs. It may be just easier to use Travis if it is already there and you guys don't have preference.

**Comment by arschles** [comment]
+1 on Travis. @mbohlool I don't seem to have access on Travis to turn on tests for this repo. If you could do so, I can add the travis file, etc...

**Comment by mbohlool** [comment]
Just enabled it for all repos. If you add .travis file, it should work.

**Comment by arschles** [comment]
thanks @mbohlool !
