### ISSUE TITLE
Reusable kube resource interfaces

### ISSUE THREAD

**Issue by whitecolor** [kubernetes-client/typescript#27]
I think it is worth making separate library for kubernetes resources definitions. I have one for my own, look something like this:

```ts
/**
 * https://kubernetes.io/docs/api-reference/v1.6/#deploymentspec-v1beta1-apps
 */
export interface DeploymentSpec {
  /**
   * Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready)
   */
  minReadySeconds?: number,
  /**
   * Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1.
   */
  replicas?: number,
  /**
   * The number of old ReplicaSets to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 2.
   */
  revisionHistoryLimit?: number,
  /**
   * The config this deployment is rolling back to. Will be cleared after rollback is done.
   */
  rollbackTo?: RollbackConfig,
  /**
   * Label selector for pods. Existing ReplicaSets whose pods are selected by this will be the ones affected by this deployment.
   */
  selector?: LabelSelector,
  /**
   * The deployment strategy to use to replace existing pods with new ones.
   */
  strategy?: DeploymentStrategy
  /**
   * Template describes the pods that will be created.
   */
  template: PodTemplateSpec
}

export interface Deployment extends Resource {
  apiVersion: 'extensions/v1beta1'
  kind: 'Deployment',
  spec: DeploymentSpec
}
```

Though they are manually created, not generated as I assume can be.

I use those interfaces to created helm charts or kube configs (JS results are converted to yalm configs and applied to server). I find using Typescript for make cluster resources configs much more convenient, flexible and safe then authoring configs in native YAML format.

**Comment by arschles** [comment]
@whitecolor - if we generated the resource classes from the OpenAPI spec, would that let you use this library completely in your programs that create helm charts/kube configs?

**Comment by whitecolor** [comment]
@arschles Why classes for Resouces not interfaces?

**Comment by brendandburns** [comment]
@whitecolor I think this requires creating a new OpenAPI based generator.

Definitely a possiblity, but a pretty big project...

Another thing is that OpenAPI 3 will support inheritance/parent objects from what I hear, so that may help with this use case too...

**Comment by arschles** [comment]
Sorry for the big delay here. +1 to @brendanburns 

Much of the work would be writing new templates for the openapi generator and testing the generated code

**Comment by brendandburns** [comment]
Closing because this repo is deprecated in favor of https://github.com/kubernetes-client/javascript
