### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by vforv** [kubernetes-client/typescript#31]
I only see this code
```
import config = require('./config');

let k8sApi = config.Config.defaultClient();

k8sApi.listNamespacedPod('default')
    .then((res) => {
        console.log(res.body);
    });
```

Where is config file how it looks like?
How to authenticate with plain user and password and how with tokens? 
How  to get instance?

**Comment by brendandburns** [comment]
Closing because this repo is deprecated in favor of https://github.com/kubernetes-client/javascript
