### ISSUE TITLE
Move this repo to kubernetes-retired?

### ISSUE THREAD

**Issue by spiffxp** [kubernetes-client/typescript#33]
>This library has been deprecated and merged with the javascript library project.
>Please file issues and PRs against that project, this is retained for historical reasons only.

This is the exact reason https://github.com/kubernetes-retired exists.  Should we move this to kubernetes-retired/kubernetes-client-typescript?

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/issues/1721

**Comment by brendandburns** [comment]
Yep, let's shut it down.

Thanks!
